### ISSUE TITLE
Run tests under Travis

### ISSUE THREAD

**Issue by inglesp** [PyconUK/ironcage#2]

**Comment by meshy** [comment]
I'm happy to look into this if you like. First attempt at running the tests locally has failed though, as I don't have a `STRIPE_API_KEY_PUBLISHABLE` env var. Would you mind if I relax the setting to be `os.environ.get()` instead of a direct dict lookup?

**Comment by meshy** [comment]
Also, I'd understand if you'd rather get along with this on your own for a while before I butt in! `;)

**Comment by inglesp** [comment]
@meshy Would love you to butt in!

I'm open to suggestions for how we handle environment variables.  I've been using [django-dotenv](https://github.com/jpadilla/django-dotenv) with a `.env` file, and there's a checked-in `.env.example` that has the necessary variables set to dummy values.  I'd suggest copying `.env.example` to `.env` before starting development.  This is a pattern I've used quite successfully in the past, but I'd be interested in alternative approaches.

**Comment by meshy** [comment]
Good news!

Thanks for letting me know about the `.env.example`. I'll attempt to get the tests running with that.

I tend to configure a `Makefile` that will run the website with `make run` and the tests with `make test`. This defines sensible defaults for local development in a way that can be overridden with env vars (say, with `dotenv`, `envdir`, or just `export`ing the variables as desired.

That said, I'm happy to follow your lead on this, so unless you'd like me to open a PR so you can see what I mean, I'll just use the `.env` file as you've suggested.

**Comment by meshy** [comment]
I should probably add: on top of that, I also add a [check](https://docs.djangoproject.com/en/1.11/topics/checks/) to make sure that the appropriate env vars have been correctly set in production.
