### ISSUE TITLE
Set up GitHub to prevent pushing to master

### ISSUE THREAD

**Issue by inglesp** [PyconUK/ironcage#3]

**Comment by meshy** [comment]
I've changed the settings to the following:

![screenshot from 2017-05-26 20-56-11](https://cloud.githubusercontent.com/assets/767671/26510567/d34d3b82-4255-11e7-9095-23e93cda8d3f.png)

Is this what you had in mind? Would you like me to require TravisCI to be successful (ie, "require status checks"), or any of the others too?

**Comment by inglesp** [comment]
This looks fine for now, thanks!
