### ISSUE TITLE
Set up code quality metric checking

### ISSUE THREAD

**Issue by inglesp** [PyconUK/ironcage#5]

**Comment by meshy** [comment]
Any particulars in mind? `flake8` as part of the tests is easy to set this up on TravisCI, but I imagine the particulars (like maximum line length) will need to be discussed.

Perhaps something like [quantifiedcode](https://www.quantifiedcode.com/) too?

**Comment by inglesp** [comment]
I'm happy with `flake8` + TravisCI for now.
