### ISSUE TITLE
User can end up with multiple tickets

### ISSUE THREAD

**Issue by evildmp** [PyconUK/ironcage#54]
* Order no. 4D0C
* includes a ticket with a bogus address
* After payment:
    * system emailed the admin: "unknown or illegal alias: <my address>@mac.com"
    * I got a 500 error from the application
    * the system no longer works for the user who placed the order - no links to functions are available
    * this persists after logging out and in again

<img width="1190" alt="screenshot 2017-06-24 09 20 53" src="https://user-images.githubusercontent.com/86222/27507088-08d3d114-58c0-11e7-9053-5643721a6b07.png">

* So far, I can't replicate with a bogus address (e.g. http://ironcage-dev.herokuapp.com/tickets/orders/719E/)

**Comment by inglesp** [comment]
Your user has ended up with two tickets, which the system assumes should never happen.  This would explain why the links are missing on the page, as a call to `user.tickets.get()` blows up in a template, which is then ignored.  (Why oh why does the Django template language swallow exceptions when `DEBUG = False`?)

I expect this is the cause of the 500 exception, although I can't be sure as we haven't set up logging properly yet.  (Why oh why does Django not log exceptions to the console by default when `DEBUG = False`?)

The only way I can see for this to have happened is for you to have started two orders in parallel.  We should enforce that a user can only have one ticket at the database level.

The bogus address is almost certainly a red herring here, so I'll rename the issue.

**Comment by inglesp** [comment]
Fixed through:
 * 46b611b3756616e2d99aa16e4176e3ad1043dd00
 * 399762ab9ad87df9913bc9e1fc4e498ace7ba457
 * ba5dfe402bd91eff4b16a5a8626911d8f06276a1
 * fac43819825caed3931a625c21ab4fcb64ff3bcd
