### ISSUE TITLE
No link to my profile after signing up

### ISSUE THREAD

**Issue by alexwlchan** [PyconUK/ironcage#55]
After I sign up for tickets, I get a warning message:

> Your profile is incomplete

Okay, great, let’s go do something about that! Err… how? There’s no link in the warning message, nor is there anything labelled “profile” that I might try to go to for rectifying this error.

![screen shot 2017-06-26 at 07 08 59](https://user-images.githubusercontent.com/301220/27526542-9cf26d4a-5a3e-11e7-8836-c43e509a1f86.png)

**Comment by inglesp** [comment]
Good spot.  We should only show this message if a user has a ticket.
