### ISSUE TITLE
Link to CfP and financial assistance is broken immediately after I sign up

### ISSUE THREAD

**Issue by alexwlchan** [PyconUK/ironcage#56]
I created a new account from http://ironcage-dev.herokuapp.com/accounts/register/?next=/tickets/orders/new/, and immediately afterwards I’m taken to a page with three options:

> * Order conference tickets
> * Make a submission to our Call for Participation
> * Apply for financial assistance

Of those, only the first link seems to be working.

**Comment by inglesp** [comment]
This is expected.  Once #35 and #47 are done, these links will have something to link to.
