### ISSUE TITLE
Set up domain to send mail from

### ISSUE THREAD

**Issue by inglesp** [PyconUK/ironcage#60]
We need to add and then verify a domain that we can send mail from, via the Mailgun control panel which can be accessed from Heroku's application dashboard.  We have already done this for the staging app, so this will hopefully be straightforward.

This can be tested with `heroku run --app ironcage python manage.py sendtestemail [email_addr]`.

**Comment by ghickman** [comment]
Staging and Production now both sending test emails.  Both are using their respective app domain names (`hq[-staging].pyconuk.org`) for DNS verification under the hood.  I've also changed the email test command (see eec89b2) to use this domain as it should provide better deliverability (I got all test emails fine via Fastmail a server-from and actual-from mismatch has bitten me in the past).
