### ISSUE TITLE
Add UKPA Trustee Nomination

### ISSUE THREAD

**Issue by meatballs** [PyconUK/ironcage#72]
We should add the ability for users to stand for election to the UKPA board of trustees.

The form which they complete should include:

* A photo
* A statement supporting their candidacy
* a tick box to confirm that they are eligible to be a trustee of a UK charity
* a tick box to confirm they are available for the AGM and the initial trustees' meeting

There should then be a page on the main website where the each candidate's 'manifesto' can be viewed.

**Comment by inglesp** [comment]
I reckon we can close this!
